name: release envps

on:
  push:
    tags:
      - '[0-9]*.[0-9]*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: install targets
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
      - name: build
        run: make
      - name: rename artifact
        run: mv envps envps-macos-arm64-x86_64
      - uses: actions/upload-artifact@v7
        with:
          path: envps-macos-arm64-x86_64
          archive: false
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install musl target
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get update && sudo apt-get install -y musl-tools
      - name: build
        run: make
      - name: rename artifact
        run: mv envps envps-linux-x86_64
      - uses: actions/upload-artifact@v7
        with:
          path: envps-linux-x86_64
          archive: false
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: '14.2'
          run: |
            sudo pkg install -y gmake ca_root_nss
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            . "$HOME/.cargo/env"
            gmake
      - name: rename artifact
        run: mv envps envps-freebsd-x86_64
      - uses: actions/upload-artifact@v7
        with:
          path: envps-freebsd-x86_64
          archive: false
  build-netbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: netbsd
          version: '10.1'
          run: |
            sudo pkgin -y install gmake mozilla-rootcerts-openssl
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            . "$HOME/.cargo/env"
            gmake
      - name: rename artifact
        run: mv envps envps-netbsd-x86_64
      - uses: actions/upload-artifact@v7
        with:
          path: envps-netbsd-x86_64
          archive: false
  release:
    needs: [build-macos, build-linux, build-freebsd, build-netbsd]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
      - name: create release
        run: gh release create ${{ github.ref_name }} **/envps-*-* --repo ${{ github.repository }} --title "envps ${{ github.ref_name }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
